name: Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Hello
        run: echo hello

      - name: Checkout sources
        uses: actions/checkout@v1
      
      - name: Log
        run: git log
